### PR TITLE
Kan 19 create logging for flask app

### PR DESCRIPTION
**Pull request by maciusmajor**

### CODE REVIEW

**Review by JanKaczmarski — CHANGES_REQUESTED** [review]
Needs some improvements. Unapproved

**Comment by JanKaczmarski** [comment]
Provide proofs on code working

**Comment by JanKaczmarski** [comment]
Create tests for this logger. Simple unit test to check if after causing some action on flask_app this certain change is recorded in `.log` file

**Comment by maciusmajor** [comment]
Made tests

**Comment by JanKaczmarski** [comment]
@maciusmajor resolve merge conflict

**Comment by maciusmajor** [comment]
Before:
image
Action:
image
After:
image

**Review by JanKaczmarski — APPROVED** [review]

**Pull request merged**
